#+title: Publications
#+layout: about

** 2023

- Hou, Jian, Zhiyong Chen, Zhiyun Lin, Chunling Wei, Junzheng Zheng, /Fangyuan Wang/, Mengfan Xiang, and Yujie Xie. "Resilient consensus via weight learning and its application in fault-tolerant clock synchronization." IEEE Transactions on Control of Network Systems (2023).

** 2022

- Wei Jiawen, /Fangyuan Wang/, Wanxin Zeng, Wenwei Lin, and Ning Gui. "An Embedded Feature Selection Framework for Control." In Proceedings of the 28th ACM SIGKDD Conference on Knowledge Discovery and Data Mining, pp. 1979-1988. 2022.

- Wei Jiawen, Zhifeng Qiu, /Fangyuan Wang/, Wenwei Lin, Ning Gui, and Weihua Gui. "Understanding via Exploration: Discovery of Interpretable Features With Deep Reinforcement Learning." IEEE Transactions on Neural Networks and Learning Systems (2022).

- Hou Jian, /Wang Fangyuan/, Chunling Wei, Hongyun Huang, Yong Hu, and Ning Gui. "Credibility assessment based Byzantine-resilient decentralized learning." IEEE Transactions on Dependable and Secure Computing (2022).

** 2021

- Hou Jian, /Fangyuan Wang/, Lili Wang, and Zhiyong Chen. "Reinforcement learning based multi-agent resilient control: From deep neural networks to an adaptive law." In Proceedings of the AAAI Conference on Artificial Intelligence, vol. 35, no. 9, pp. 7737-7745. 2021.
